# Generated by Django 2.1.7 on 2019-02-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0003_auto_20190226_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplebet',
            name='player1_win1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_win2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_win1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_win2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_win1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_win2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
