# Generated by Django 2.1.7 on 2019-02-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0004_auto_20190226_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_players', models.IntegerField(blank=True, default=None, null=True)),
                ('probability', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_fwin1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_fwin2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_fwin1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_fwin2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_fwin1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_fwin2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
