# Generated by Django 2.1.7 on 2019-02-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0005_auto_20190226_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbet',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
