# Generated by Django 2.1.7 on 2019-02-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0007_auto_20190227_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplebet',
            name='commission1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='commission2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
