# Generated by Django 2.1.7 on 2019-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0009_auto_20190227_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplebet',
            name='player1_fwin1',
        ),
        migrations.RemoveField(
            model_name='triplebet',
            name='player1_fwin2',
        ),
        migrations.RemoveField(
            model_name='triplebet',
            name='player2_fwin1',
        ),
        migrations.RemoveField(
            model_name='triplebet',
            name='player2_fwin2',
        ),
        migrations.RemoveField(
            model_name='triplebet',
            name='player3_fwin1',
        ),
        migrations.RemoveField(
            model_name='triplebet',
            name='player3_fwin2',
        ),
        migrations.AddField(
            model_name='doublebet',
            name='garanty_moneyback1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='garanty_moneyback2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player1_fact_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player1_fact_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player2_fact_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player2_fact_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='garanty_moneyback1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='garanty_moneyback2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='garanty_moneyback3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_fact_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_fact_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_fact_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_fact_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_fact_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_fact_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
