# Generated by Django 2.1.7 on 2019-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play42_proto', '0010_auto_20190228_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublebet',
            name='player1_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player1_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player2_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doublebet',
            name='player2_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player1_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player2_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_coef1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='triplebet',
            name='player3_coef2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
